# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 291dbc9396a6b8730e3c953867e65c348b492722b34abdb2230ce9318879b0cc272e660e66e6f58673ee29996c696816f2d04fa2866ab0ab38e70d0f6564023b

test:
  secret_key_base: 1516949169264202fb9b1a004a7fccf683c498cec2698b0afc7b771c282d6dd16116ee4621d647b0bc775b80ef65045318c7fdb226a010315b25e928c191c8bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
